; ------------------------------------------------------------------------------
; Sonic CD (1993) Disassembly
; By Devon Artmeier
; ------------------------------------------------------------------------------

SUB_CPU			equ 1

; ------------------------------------------------------------------------------

	include	"mcd_sub.inc"
	include	"system.inc"
	include	"system_symbols.inc"
	include	"system_ids.inc"
	include	"backup_ram.inc"
	include	"cdda_ids.inc"
	include	"pcm_sound_ids.inc"
	include	"da_garden.inc"
	include	"special_stage.inc"

; ------------------------------------------------------------------------------
