; ------------------------------------------------------------------------------
; Sonic CD (1993) Disassembly
; By Devon Artmeier
; ------------------------------------------------------------------------------

MAIN_CPU		equ 1

; ------------------------------------------------------------------------------

	include	"mcd_main.inc"
	include	"system_ids.inc"
	include	"backup_ram.inc"
	include	"fm_sound_ids.inc"
	include	"fm_driver.inc"
	include	"mmd.inc"
	include	"game_variables.inc"
	include	"da_garden.inc"
	include	"special_stage.inc"

; ------------------------------------------------------------------------------
